### ISSUE TITLE
Notified when stories finished

### ISSUE THREAD

**Issue by ahmed-shehataa** [raipankaj/Stories#1]
How can I get notified when the stories list have been finished to do some custom action?

**Comment by raipankaj** [comment]
Support for this is added in v1.0.1 please add the following dependency
implementation 'com.github.raipankaj:Stories:1.0.1'

Snippet:
Stories(numberOfPages = listOfImages.size, onComplete = { }) { index ->
        Image(painter = painterResource(id = listOfImages[index]), contentDescription = null,
            contentScale = ContentScale.Crop, modifier = Modifier.fillMaxSize())
}

onComplete will get triggered as soon as all the stories are shown.

**Comment by ahmed-shehataa** [comment]
Thank you.. that sounds great
